import numpy as np

NR_OF_BINS = 10 # MUST BE AN EVEN NUMBER SO THAT MIDDLE POINT IS ZERO. CONTROL IT.
BACKWARD_WINDOW_LENGTH = 4
FORWARD_WINDOW_LENGTH = 1
INTERPLOATION_POINTS = 1200
EXCHANGE_RATES = ['EURUSD']

FROM_TIMESTAMP = '2022-10-01 00:00'
TO_TIMESTAMP = '2022-11-01 00:00'
FFT_AC_COEFFICIENT  = 15 
LOWER_POINT = -0.005
UPPER_POINT = 0.005
THRESHOLD = 0.10

NR_OF_ENSEMBLED_MODELS = 8


RANDOM_STATE = 42
DATA_AUGMENTATION_BASE_MODEL_PATH = r'Models\Data_Augmentaiton\Base_Model'
PREPROCESSED_DATA_PATH = r'C:\Users\yunus\Desktop\Preprocessed Data'
FEATURE_ENGINEERED_DATA_PATH = r'C:\Users\yunus\Desktop\Feature Engineered Data'



NR_OF_BOUNDARIES = 128
BIN_BOUNDARIES = np.linspace(1.170, 1.185, NR_OF_BOUNDARIES) 
SIZE_OF_CHUNK = 30
ATTENTION_KEY_DIMS = 64
ATTENTION_NR_OF_HEADS = 6
ENCODER_DENSE_DIMS = 32
DROPOUT_RATE = 0
NR_OF_ENCODER_BLOCKS = 3
STOPPER_THRESHOLD = 0.18


CHECKPOINT_PATH =  r'C:\Users\yunus\Desktop\Checkpoints\DisERT'

DISERT_DATA_PATH = r'C:\Users\yunus\Desktop\DisERT Data'
